query Game($slug: String!) {
  games(filters: { slug: { eq: $slug } }) {
    ...GameDetails
  }
}

fragment GameDetails on Game {
  documentId
  slug
  name
  category
  scale
  timebox
  summary
  credits
  description
  publishedAt
  tags {
    id
    value
  }
  materials {
    id
    value
  }
  preparationSteps {
    id
    value
  }
  safety {
    id
    key
    value
  }
  defaultImage {
    name
    url
    width
    height
  }
  images {
    name
    url
    width
    height
  }
  resources {
    name
    url
  }
  firstPlayedAt {
    name
    slug
  }
  documentedBy {
    name
    slug
    avatar {
      name
      url
      width
      height
    }
  }
  proposedBy {
    name
    slug
    avatar {
      name
      url
      width
      height
    }
  }
  ratings {
    energy
    connection
    silliness
  }
}
