query Games($page: Int!, $pageSize: Int!, $category: String, $tag: String) {
  games_connection(
    sort: "name:asc"
    pagination: { page: $page, pageSize: $pageSize }
    filters: { category: { eqi: $category }, tags: { value: { eqi: $tag } } }
  ) {
    nodes {
      ...GameItem
    }
    pageInfo {
      page
      pageSize
      total
      pageCount
    }
  }
}

fragment GameItem on Game {
  documentId
  slug
  name
  summary
  timebox
  scale
  category
  proposedBy {
    name
    slug
    avatar {
      name
      url
      width
      height
    }
  }
  defaultImage {
    name
    url
    width
    height
  }
}
