query Players($page: Int!, $pageSize: Int!, $position: String) {
  players_connection(
    sort: "name:asc"
    pagination: { page: $page, pageSize: $pageSize }
    filters: { position: { eqi: $position } }
  ) {
    nodes {
      ...PlayerItem
    }
    pageInfo {
      page
      pageSize
      total
      pageCount
    }
  }
}

fragment PlayerItem on Player {
  documentId
  slug
  name
  position
  avatar {
    name
    url
    width
    height
  }
  socialNetworks {
    id
    url
    type
  }
}
