query Event($slug: String!) {
  events(filters: { slug: { eq: $slug } }) {
    ...EventDetails
  }
}

fragment EventDetails on Event {
  documentId
  slug
  name
  start
  end
  timezone
  status
  description
  contactEmail
  defaultImage {
    name
    url
    width
    height
  }
  images {
    name
    url
    width
    height
  }
  location {
    name
    country
    location
  }
  venue {
    name
    website
    location
    addressDetails
  }
  timetable {
    id
    day
    description
    timeslots {
      id
      time
      description
    }
  }
  registration {
    link
    widgetCode
  }
  sponsorships {
    id
    category
    sponsors {
      name
      url
      logo {
        name
        url
        width
        height
      }
      socialNetworks {
        id
        type
        url
      }
    }
  }
  hosts(sort: "name") {
    ...PlayerItem
  }
  mentors(sort: "name") {
    ...PlayerItem
  }
  players(sort: "name") {
    ...PlayerItem
  }
  media {
    id
    url
    type
  }
}
