query Events(
  $page: Int!
  $pageSize: Int!
  $status: String
  $location: String
  $country: String
) {
  events_connection(
    sort: "start:desc"
    pagination: { page: $page, pageSize: $pageSize }
    filters: {
      status: { eqi: $status }
      location: { slug: { eqi: $location }, country: { eqi: $country } }
    }
  ) {
    nodes {
      ...EventItem
    }
    pageInfo {
      page
      pageSize
      total
      pageCount
    }
  }
}

query UpcomingEvents($today: DateTime!) {
  events(sort: "start:asc", filters: { end: { gte: $today } }) {
    ...EventItem
  }
}

fragment EventItem on Event {
  documentId
  slug
  name
  start
  end
  timezone
  status
  defaultImage {
    name
    url
    width
    height
  }
  location {
    name
    country
  }
}
