query Article($slug: String!) {
  articles(filters: { slug: { eq: $slug } }) {
    ...ArticleDetails
  }
}

fragment ArticleDetails on Article {
  documentId
  slug
  title
  category
  summary
  publishedAt
  updatedAt
  cannonical
  tags {
    value
  }
  defaultImage {
    name
    url
    width
    height
  }
  images {
    name
    url
    width
    height
  }
  author {
    name
    slug
    position
    tagline
    avatar {
      name
      url
      width
      height
    }
  }
  content
}
