query Articles($page: Int!, $pageSize: Int!, $category: String, $tag: String) {
  articles_connection(
    sort: "publishedAt:desc"
    pagination: { page: $page, pageSize: $pageSize }
    filters: { category: { eqi: $category }, tags: { value: { eqi: $tag } } }
  ) {
    nodes {
      ...ArticleItem
    }
    pageInfo {
      page
      pageSize
      total
      pageCount
    }
  }
}

fragment ArticleItem on Article {
  documentId
  slug
  title
  summary
  category
  publishedAt
  defaultImage {
    name
    url
    width
    height
  }
  author {
    slug
    name
    avatar {
      name
      url
      width
      height
    }
  }
}
