/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthChangePasswordPostRequest
 */
export interface AuthChangePasswordPostRequest {
  /**
   *
   * @type {string}
   * @memberof AuthChangePasswordPostRequest
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof AuthChangePasswordPostRequest
   */
  currentPassword: string;
  /**
   *
   * @type {string}
   * @memberof AuthChangePasswordPostRequest
   */
  passwordConfirmation: string;
}

/**
 * Check if a given object implements the AuthChangePasswordPostRequest interface.
 */
export function instanceOfAuthChangePasswordPostRequest(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && "password" in value;
  isInstance = isInstance && "currentPassword" in value;
  isInstance = isInstance && "passwordConfirmation" in value;

  return isInstance;
}

export function AuthChangePasswordPostRequestFromJSON(
  json: any
): AuthChangePasswordPostRequest {
  return AuthChangePasswordPostRequestFromJSONTyped(json, false);
}

export function AuthChangePasswordPostRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthChangePasswordPostRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    password: json["password"],
    currentPassword: json["currentPassword"],
    passwordConfirmation: json["passwordConfirmation"],
  };
}

export function AuthChangePasswordPostRequestToJSON(
  value?: AuthChangePasswordPostRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    password: value.password,
    currentPassword: value.currentPassword,
    passwordConfirmation: value.passwordConfirmation,
  };
}
