/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationRequestData } from "./EventLocationRequestData";
import {
  EventLocationRequestDataFromJSON,
  EventLocationRequestDataFromJSONTyped,
  EventLocationRequestDataToJSON,
} from "./EventLocationRequestData";

/**
 *
 * @export
 * @interface EventLocationRequest
 */
export interface EventLocationRequest {
  /**
   *
   * @type {EventLocationRequestData}
   * @memberof EventLocationRequest
   */
  data: EventLocationRequestData;
}

/**
 * Check if a given object implements the EventLocationRequest interface.
 */
export function instanceOfEventLocationRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;

  return isInstance;
}

export function EventLocationRequestFromJSON(json: any): EventLocationRequest {
  return EventLocationRequestFromJSONTyped(json, false);
}

export function EventLocationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: EventLocationRequestDataFromJSON(json["data"]),
  };
}

export function EventLocationRequestToJSON(
  value?: EventLocationRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocationRequestDataToJSON(value.data),
  };
}
