/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations {
  /**
   *
   * @type {Array<any>}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations
   */
  data?: Array<any>;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data") ? undefined : json["data"],
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: value.data,
  };
}
