/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration
   */
  link?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration
   */
  widgetCode?: string;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    link: !exists(json, "link") ? undefined : json["link"],
    widgetCode: !exists(json, "widgetCode") ? undefined : json["widgetCode"],
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    link: value.link,
    widgetCode: value.widgetCode,
  };
}
