/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles {
  /**
   *
   * @type {Array<EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner>}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles
   */
  data?: Array<EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner>;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSON
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFiles | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerToJSON
          ),
  };
}
