/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  url?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  logo?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  socialNetworks?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributesFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    url: !exists(json, "url") ? undefined : json["url"],
    logo: !exists(json, "logo")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON(
          json["logo"]
        ),
    socialNetworks: !exists(json, "socialNetworks")
      ? undefined
      : (json["socialNetworks"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributesToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerSponsorsDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    url: value.url,
    logo: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON(
      value.logo
    ),
    socialNetworks:
      value.socialNetworks === undefined
        ? undefined
        : (value.socialNetworks as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON
          ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
