/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseDataItemLocalized } from "./EventListResponseDataItemLocalized";
import {
  EventListResponseDataItemLocalizedFromJSON,
  EventListResponseDataItemLocalizedFromJSONTyped,
  EventListResponseDataItemLocalizedToJSON,
} from "./EventListResponseDataItemLocalized";

/**
 *
 * @export
 * @interface EventListResponseDataItemAttributesLocalizations
 */
export interface EventListResponseDataItemAttributesLocalizations {
  /**
   *
   * @type {Array<EventListResponseDataItemLocalized>}
   * @memberof EventListResponseDataItemAttributesLocalizations
   */
  data?: Array<EventListResponseDataItemLocalized>;
}

/**
 * Check if a given object implements the EventListResponseDataItemAttributesLocalizations interface.
 */
export function instanceOfEventListResponseDataItemAttributesLocalizations(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventListResponseDataItemAttributesLocalizationsFromJSON(
  json: any
): EventListResponseDataItemAttributesLocalizations {
  return EventListResponseDataItemAttributesLocalizationsFromJSONTyped(
    json,
    false
  );
}

export function EventListResponseDataItemAttributesLocalizationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventListResponseDataItemAttributesLocalizations {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          EventListResponseDataItemLocalizedFromJSON
        ),
  };
}

export function EventListResponseDataItemAttributesLocalizationsToJSON(
  value?: EventListResponseDataItemAttributesLocalizations | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            EventListResponseDataItemLocalizedToJSON
          ),
  };
}
