/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner
   */
  type?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerTypeEnum;
}

/**
 * @export
 */
export const EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerTypeEnum =
  {
    Twitter: "Twitter",
    LinkedIn: "LinkedIn",
    Facebook: "Facebook",
    Youtube: "Youtube",
    Instagram: "Instagram",
    Xing: "Xing",
    Email: "Email",
    Website: "Website",
    Wikipedia: "Wikipedia",
    Vimeo: "Vimeo",
    Other: "Other",
  } as const;
export type EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerTypeEnum =
  typeof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerTypeEnum[keyof typeof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerTypeEnum];

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    url: !exists(json, "url") ? undefined : json["url"],
    type: !exists(json, "type") ? undefined : json["type"],
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    url: value.url,
    type: value.type,
  };
}
