/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderData } from "./EventLocalizationResponseImagesDataInnerAttributesFolderData";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderData";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolder
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolder {
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderData}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolder
   */
  data?: EventLocalizationResponseImagesDataInnerAttributesFolderData;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolder interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolder(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolder {
  return EventLocalizationResponseImagesDataInnerAttributesFolderFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolder {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataFromJSON(
          json["data"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolder | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocalizationResponseImagesDataInnerAttributesFolderDataToJSON(
      value.data
    ),
  };
}
