/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner
   */
  time?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner
   */
  description?: string;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInnerFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    time: !exists(json, "time") ? undefined : json["time"],
    description: !exists(json, "description") ? undefined : json["description"],
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInnerToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerTimeslotsInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    time: value.time,
    description: value.description,
  };
}
