/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  action?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  subject?: string;
  /**
   *
   * @type {any}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  properties?: any | null;
  /**
   *
   * @type {any}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  conditions?: any | null;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  role?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    action: !exists(json, "action") ? undefined : json["action"],
    subject: !exists(json, "subject") ? undefined : json["subject"],
    properties: !exists(json, "properties") ? undefined : json["properties"],
    conditions: !exists(json, "conditions") ? undefined : json["conditions"],
    role: !exists(json, "role")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["role"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    action: value.action,
    subject: value.subject,
    properties: value.properties,
    conditions: value.conditions,
    role: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
      value.role
    ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
