/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions {
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInner>}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions
   */
  data?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInner>;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInnerFromJSON
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsDataInnerToJSON
          ),
  };
}
