/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImages } from "./EventLocalizationResponseImages";
import {
  EventLocalizationResponseImagesFromJSON,
  EventLocalizationResponseImagesFromJSONTyped,
  EventLocalizationResponseImagesToJSON,
} from "./EventLocalizationResponseImages";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { EventLocalizationResponseLocation } from "./EventLocalizationResponseLocation";
import {
  EventLocalizationResponseLocationFromJSON,
  EventLocalizationResponseLocationFromJSONTyped,
  EventLocalizationResponseLocationToJSON,
} from "./EventLocalizationResponseLocation";
import type { EventResponseDataObjectAttributesLocalizations } from "./EventResponseDataObjectAttributesLocalizations";
import {
  EventResponseDataObjectAttributesLocalizationsFromJSON,
  EventResponseDataObjectAttributesLocalizationsFromJSONTyped,
  EventResponseDataObjectAttributesLocalizationsToJSON,
} from "./EventResponseDataObjectAttributesLocalizations";
import type { EventsMediaComponent } from "./EventsMediaComponent";
import {
  EventsMediaComponentFromJSON,
  EventsMediaComponentFromJSONTyped,
  EventsMediaComponentToJSON,
} from "./EventsMediaComponent";
import type { EventsSponsorshipComponent } from "./EventsSponsorshipComponent";
import {
  EventsSponsorshipComponentFromJSON,
  EventsSponsorshipComponentFromJSONTyped,
  EventsSponsorshipComponentToJSON,
} from "./EventsSponsorshipComponent";
import type { EventsTimetableComponent } from "./EventsTimetableComponent";
import {
  EventsTimetableComponentFromJSON,
  EventsTimetableComponentFromJSONTyped,
  EventsTimetableComponentToJSON,
} from "./EventsTimetableComponent";
import type { RegistrationRegistrationComponent } from "./RegistrationRegistrationComponent";
import {
  RegistrationRegistrationComponentFromJSON,
  RegistrationRegistrationComponentFromJSONTyped,
  RegistrationRegistrationComponentToJSON,
} from "./RegistrationRegistrationComponent";

/**
 *
 * @export
 * @interface EventResponseDataObjectAttributes
 */
export interface EventResponseDataObjectAttributes {
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  slug?: string;
  /**
   *
   * @type {Date}
   * @memberof EventResponseDataObjectAttributes
   */
  start?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventResponseDataObjectAttributes
   */
  end?: Date;
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  status?: EventResponseDataObjectAttributesStatusEnum;
  /**
   *
   * @type {EventLocalizationResponseImages}
   * @memberof EventResponseDataObjectAttributes
   */
  images?: EventLocalizationResponseImages;
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  contactEmail?: string;
  /**
   *
   * @type {Array<EventsTimetableComponent>}
   * @memberof EventResponseDataObjectAttributes
   */
  timetable?: Array<EventsTimetableComponent>;
  /**
   *
   * @type {RegistrationRegistrationComponent}
   * @memberof EventResponseDataObjectAttributes
   */
  registration?: RegistrationRegistrationComponent;
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  description?: string;
  /**
   *
   * @type {EventLocalizationResponseLocation}
   * @memberof EventResponseDataObjectAttributes
   */
  location?: EventLocalizationResponseLocation;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventResponseDataObjectAttributes
   */
  venue?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventResponseDataObjectAttributes
   */
  players?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventResponseDataObjectAttributes
   */
  hosts?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventResponseDataObjectAttributes
   */
  mentors?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {Array<EventsSponsorshipComponent>}
   * @memberof EventResponseDataObjectAttributes
   */
  sponsorships?: Array<EventsSponsorshipComponent>;
  /**
   *
   * @type {Array<EventsMediaComponent>}
   * @memberof EventResponseDataObjectAttributes
   */
  media?: Array<EventsMediaComponent>;
  /**
   *
   * @type {Date}
   * @memberof EventResponseDataObjectAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventResponseDataObjectAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventResponseDataObjectAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventResponseDataObjectAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventResponseDataObjectAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventResponseDataObjectAttributesLocalizations}
   * @memberof EventResponseDataObjectAttributes
   */
  localizations?: EventResponseDataObjectAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof EventResponseDataObjectAttributes
   */
  locale?: string;
}

/**
 * @export
 */
export const EventResponseDataObjectAttributesStatusEnum = {
  Announced: "Announced",
  Open: "Open",
  Over: "Over",
  Cancelled: "Cancelled",
} as const;
export type EventResponseDataObjectAttributesStatusEnum =
  typeof EventResponseDataObjectAttributesStatusEnum[keyof typeof EventResponseDataObjectAttributesStatusEnum];

/**
 * Check if a given object implements the EventResponseDataObjectAttributes interface.
 */
export function instanceOfEventResponseDataObjectAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventResponseDataObjectAttributesFromJSON(
  json: any
): EventResponseDataObjectAttributes {
  return EventResponseDataObjectAttributesFromJSONTyped(json, false);
}

export function EventResponseDataObjectAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventResponseDataObjectAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    slug: !exists(json, "slug") ? undefined : json["slug"],
    start: !exists(json, "start") ? undefined : new Date(json["start"]),
    end: !exists(json, "end") ? undefined : new Date(json["end"]),
    status: !exists(json, "status") ? undefined : json["status"],
    images: !exists(json, "images")
      ? undefined
      : EventLocalizationResponseImagesFromJSON(json["images"]),
    contactEmail: !exists(json, "contactEmail")
      ? undefined
      : json["contactEmail"],
    timetable: !exists(json, "timetable")
      ? undefined
      : (json["timetable"] as Array<any>).map(EventsTimetableComponentFromJSON),
    registration: !exists(json, "registration")
      ? undefined
      : RegistrationRegistrationComponentFromJSON(json["registration"]),
    description: !exists(json, "description") ? undefined : json["description"],
    location: !exists(json, "location")
      ? undefined
      : EventLocalizationResponseLocationFromJSON(json["location"]),
    venue: !exists(json, "venue")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["venue"]
        ),
    players: !exists(json, "players")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["players"]
        ),
    hosts: !exists(json, "hosts")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["hosts"]
        ),
    mentors: !exists(json, "mentors")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["mentors"]
        ),
    sponsorships: !exists(json, "sponsorships")
      ? undefined
      : (json["sponsorships"] as Array<any>).map(
          EventsSponsorshipComponentFromJSON
        ),
    media: !exists(json, "media")
      ? undefined
      : (json["media"] as Array<any>).map(EventsMediaComponentFromJSON),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    publishedAt: !exists(json, "publishedAt")
      ? undefined
      : new Date(json["publishedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
    localizations: !exists(json, "localizations")
      ? undefined
      : EventResponseDataObjectAttributesLocalizationsFromJSON(
          json["localizations"]
        ),
    locale: !exists(json, "locale") ? undefined : json["locale"],
  };
}

export function EventResponseDataObjectAttributesToJSON(
  value?: EventResponseDataObjectAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    slug: value.slug,
    start: value.start === undefined ? undefined : value.start.toISOString(),
    end: value.end === undefined ? undefined : value.end.toISOString(),
    status: value.status,
    images: EventLocalizationResponseImagesToJSON(value.images),
    contactEmail: value.contactEmail,
    timetable:
      value.timetable === undefined
        ? undefined
        : (value.timetable as Array<any>).map(EventsTimetableComponentToJSON),
    registration: RegistrationRegistrationComponentToJSON(value.registration),
    description: value.description,
    location: EventLocalizationResponseLocationToJSON(value.location),
    venue:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.venue
      ),
    players: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.players
    ),
    hosts: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.hosts
    ),
    mentors: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.mentors
    ),
    sponsorships:
      value.sponsorships === undefined
        ? undefined
        : (value.sponsorships as Array<any>).map(
            EventsSponsorshipComponentToJSON
          ),
    media:
      value.media === undefined
        ? undefined
        : (value.media as Array<any>).map(EventsMediaComponentToJSON),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt:
      value.publishedAt === undefined
        ? undefined
        : value.publishedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
    localizations: EventResponseDataObjectAttributesLocalizationsToJSON(
      value.localizations
    ),
    locale: value.locale,
  };
}
