/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData
   */
  id?: number;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData
   */
  attributes?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesToJSON(
        value.attributes
      ),
  };
}
