/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy {
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy
   */
  data?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSON(
          json["data"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataToJSON(
      value.data
    ),
  };
}
