/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  type?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  permissions?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissions;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  users?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    type: !exists(json, "type") ? undefined : json["type"],
    permissions: !exists(json, "permissions")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsFromJSON(
          json["permissions"]
        ),
    users: !exists(json, "users")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["users"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    type: value.type,
    permissions:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesPermissionsToJSON(
        value.permissions
      ),
    users: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.users
    ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
