/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationData } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationData";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationDataFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationDataFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationDataToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationData";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation
 */
export interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation {
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationData}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation
   */
  data?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationData;
}

/**
 * Check if a given object implements the EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation interface.
 */
export function instanceOfEventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSON(
  json: any
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation {
  return EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSONTyped(
    json,
    false
  );
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationDataFromJSON(
          json["data"]
        ),
  };
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationToJSON(
  value?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationDataToJSON(
      value.data
    ),
  };
}
