/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationListResponseDataItemAttributes } from "./EventLocationListResponseDataItemAttributes";
import {
  EventLocationListResponseDataItemAttributesFromJSON,
  EventLocationListResponseDataItemAttributesFromJSONTyped,
  EventLocationListResponseDataItemAttributesToJSON,
} from "./EventLocationListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemLocalized
 */
export interface EventLocationListResponseDataItemLocalized {
  /**
   *
   * @type {number}
   * @memberof EventLocationListResponseDataItemLocalized
   */
  id?: number;
  /**
   *
   * @type {EventLocationListResponseDataItemAttributes}
   * @memberof EventLocationListResponseDataItemLocalized
   */
  attributes?: EventLocationListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the EventLocationListResponseDataItemLocalized interface.
 */
export function instanceOfEventLocationListResponseDataItemLocalized(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemLocalizedFromJSON(
  json: any
): EventLocationListResponseDataItemLocalized {
  return EventLocationListResponseDataItemLocalizedFromJSONTyped(json, false);
}

export function EventLocationListResponseDataItemLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocationListResponseDataItemAttributesFromJSON(json["attributes"]),
  };
}

export function EventLocationListResponseDataItemLocalizedToJSON(
  value?: EventLocationListResponseDataItemLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: EventLocationListResponseDataItemAttributesToJSON(
      value.attributes
    ),
  };
}
