/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributes } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributes";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributesFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributesFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributesToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributes";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData
 */
export interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData {
  /**
   *
   * @type {number}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData
   */
  id?: number;
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributes}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData
   */
  attributes?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributes;
}

/**
 * Check if a given object implements the EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData interface.
 */
export function instanceOfEventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSON(
  json: any
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData {
  return EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSONTyped(
    json,
    false
  );
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataToJSON(
  value?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataAttributesToJSON(
        value.attributes
      ),
  };
}
