/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEvents
 */
export interface EventLocalizationResponseLocationDataAttributesEvents {
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInner>}
   * @memberof EventLocalizationResponseLocationDataAttributesEvents
   */
  data?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInner>;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEvents interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEvents(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEvents {
  return EventLocalizationResponseLocationDataAttributesEventsFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEvents {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerFromJSON
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEvents | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerToJSON
          ),
  };
}
