/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImages } from "./EventLocalizationResponseImages";
import {
  EventLocalizationResponseImagesFromJSON,
  EventLocalizationResponseImagesFromJSONTyped,
  EventLocalizationResponseImagesToJSON,
} from "./EventLocalizationResponseImages";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayers } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayers";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayers";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInner";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInner";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
 */
export interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  slug?: string;
  /**
   *
   * @type {Date}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  start?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  end?: Date;
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  status?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesStatusEnum;
  /**
   *
   * @type {EventLocalizationResponseImages}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  images?: EventLocalizationResponseImages;
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  contactEmail?: string;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInner>}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  timetable?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInner>;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  registration?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistration;
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  description?: string;
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  location?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocation;
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  venue?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayers}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  players?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayers;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  hosts?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  mentors?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInner>}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  sponsorships?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInner>;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner>}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  media?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner>;
  /**
   *
   * @type {Date}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  publishedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  localizations?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizations;
  /**
   *
   * @type {string}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributes
   */
  locale?: string;
}

/**
 * @export
 */
export const EventLocationListResponseDataItemAttributesEventsDataInnerAttributesStatusEnum =
  {
    Announced: "Announced",
    Open: "Open",
    Over: "Over",
    Cancelled: "Cancelled",
  } as const;
export type EventLocationListResponseDataItemAttributesEventsDataInnerAttributesStatusEnum =
  typeof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesStatusEnum[keyof typeof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesStatusEnum];

/**
 * Check if a given object implements the EventLocationListResponseDataItemAttributesEventsDataInnerAttributes interface.
 */
export function instanceOfEventLocationListResponseDataItemAttributesEventsDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSON(
  json: any
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributes {
  return EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    slug: !exists(json, "slug") ? undefined : json["slug"],
    start: !exists(json, "start") ? undefined : new Date(json["start"]),
    end: !exists(json, "end") ? undefined : new Date(json["end"]),
    status: !exists(json, "status") ? undefined : json["status"],
    images: !exists(json, "images")
      ? undefined
      : EventLocalizationResponseImagesFromJSON(json["images"]),
    contactEmail: !exists(json, "contactEmail")
      ? undefined
      : json["contactEmail"],
    timetable: !exists(json, "timetable")
      ? undefined
      : (json["timetable"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerFromJSON
        ),
    registration: !exists(json, "registration")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationFromJSON(
          json["registration"]
        ),
    description: !exists(json, "description") ? undefined : json["description"],
    location: !exists(json, "location")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationFromJSON(
          json["location"]
        ),
    venue: !exists(json, "venue")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSON(
          json["venue"]
        ),
    players: !exists(json, "players")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersFromJSON(
          json["players"]
        ),
    hosts: !exists(json, "hosts")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["hosts"]
        ),
    mentors: !exists(json, "mentors")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["mentors"]
        ),
    sponsorships: !exists(json, "sponsorships")
      ? undefined
      : (json["sponsorships"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerFromJSON
        ),
    media: !exists(json, "media")
      ? undefined
      : (json["media"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSON
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    publishedAt: !exists(json, "publishedAt")
      ? undefined
      : new Date(json["publishedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
    localizations: !exists(json, "localizations")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsFromJSON(
          json["localizations"]
        ),
    locale: !exists(json, "locale") ? undefined : json["locale"],
  };
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesToJSON(
  value?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    slug: value.slug,
    start: value.start === undefined ? undefined : value.start.toISOString(),
    end: value.end === undefined ? undefined : value.end.toISOString(),
    status: value.status,
    images: EventLocalizationResponseImagesToJSON(value.images),
    contactEmail: value.contactEmail,
    timetable:
      value.timetable === undefined
        ? undefined
        : (value.timetable as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesTimetableInnerToJSON
          ),
    registration:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesRegistrationToJSON(
        value.registration
      ),
    description: value.description,
    location:
      EventLocationListResponseDataItemAttributesEventsDataInnerAttributesLocationToJSON(
        value.location
      ),
    venue:
      EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueToJSON(
        value.venue
      ),
    players:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersToJSON(
        value.players
      ),
    hosts: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.hosts
    ),
    mentors: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.mentors
    ),
    sponsorships:
      value.sponsorships === undefined
        ? undefined
        : (value.sponsorships as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesSponsorshipsInnerToJSON
          ),
    media:
      value.media === undefined
        ? undefined
        : (value.media as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerToJSON
          ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    publishedAt:
      value.publishedAt === undefined
        ? undefined
        : value.publishedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
    localizations:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesLocalizationsToJSON(
        value.localizations
      ),
    locale: value.locale,
  };
}
