/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissions } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissions";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissions";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  description?: string;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  users?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissions}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  permissions?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissions;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    code: !exists(json, "code") ? undefined : json["code"],
    description: !exists(json, "description") ? undefined : json["description"],
    users: !exists(json, "users")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["users"]
        ),
    permissions: !exists(json, "permissions")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsFromJSON(
          json["permissions"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    code: value.code,
    description: value.description,
    users: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.users
    ),
    permissions:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsToJSON(
        value.permissions
      ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
