/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributes } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributes";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributes";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemAttributesEventsDataInner
 */
export interface EventLocationListResponseDataItemAttributesEventsDataInner {
  /**
   *
   * @type {number}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInner
   */
  id?: number;
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributes}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInner
   */
  attributes?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributes;
}

/**
 * Check if a given object implements the EventLocationListResponseDataItemAttributesEventsDataInner interface.
 */
export function instanceOfEventLocationListResponseDataItemAttributesEventsDataInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerFromJSON(
  json: any
): EventLocationListResponseDataItemAttributesEventsDataInner {
  return EventLocationListResponseDataItemAttributesEventsDataInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemAttributesEventsDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerToJSON(
  value?: EventLocationListResponseDataItemAttributesEventsDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      EventLocationListResponseDataItemAttributesEventsDataInnerAttributesToJSON(
        value.attributes
      ),
  };
}
