/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData
   */
  id?: number;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData
   */
  attributes?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributes;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesPlayersDataInnerAttributesUserDataAttributesRoleDataAttributesToJSON(
        value.attributes
      ),
  };
}
