/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseLocationDataAttributes } from "./EventLocalizationResponseLocationDataAttributes";
import {
  EventLocalizationResponseLocationDataAttributesFromJSON,
  EventLocalizationResponseLocationDataAttributesFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesToJSON,
} from "./EventLocalizationResponseLocationDataAttributes";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationData
 */
export interface EventLocalizationResponseLocationData {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationData
   */
  id?: number;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributes}
   * @memberof EventLocalizationResponseLocationData
   */
  attributes?: EventLocalizationResponseLocationDataAttributes;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationData interface.
 */
export function instanceOfEventLocalizationResponseLocationData(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataFromJSON(
  json: any
): EventLocalizationResponseLocationData {
  return EventLocalizationResponseLocationDataFromJSONTyped(json, false);
}

export function EventLocalizationResponseLocationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocalizationResponseLocationDataToJSON(
  value?: EventLocalizationResponseLocationData | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: EventLocalizationResponseLocationDataAttributesToJSON(
      value.attributes
    ),
  };
}
