/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner
   */
  type?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerTypeEnum;
}

/**
 * @export
 */
export const EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerTypeEnum =
  {
    Photos: "Photos",
    Videos: "Videos",
  } as const;
export type EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerTypeEnum =
  typeof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerTypeEnum[keyof typeof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerTypeEnum];

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    url: !exists(json, "url") ? undefined : json["url"],
    type: !exists(json, "type") ? undefined : json["type"],
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInnerToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesMediaInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    url: value.url,
    type: value.type,
  };
}
