/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner
 */
export interface EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner
   */
  id?: number;
  /**
   *
   * @type {object}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner
   */
  attributes?: object;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesRelatedDataInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner {
  return EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes") ? undefined : json["attributes"],
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: value.attributes,
  };
}
