/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner } from "./EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent {
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent
   */
  data?: EventLocalizationResponseImagesDataInnerAttributesRelatedDataInner;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerFromJSON(
          json["data"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocalizationResponseImagesDataInnerAttributesRelatedDataInnerToJSON(
      value.data
    ),
  };
}
