/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData } from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData";
import {
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSON,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSONTyped,
  EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataToJSON,
} from "./EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData";

/**
 *
 * @export
 * @interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue
 */
export interface EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue {
  /**
   *
   * @type {EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData}
   * @memberof EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue
   */
  data?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueData;
}

/**
 * Check if a given object implements the EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue interface.
 */
export function instanceOfEventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSON(
  json: any
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue {
  return EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSONTyped(
    json,
    false
  );
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataFromJSON(
          json["data"]
        ),
  };
}

export function EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueToJSON(
  value?: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenue | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: EventLocationListResponseDataItemAttributesEventsDataInnerAttributesVenueDataToJSON(
      value.data
    ),
  };
}
