/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributes } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributes";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributes";

/**
 *
 * @export
 * @interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner
 */
export interface EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner {
  /**
   *
   * @type {number}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner
   */
  id?: number;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributes}
   * @memberof EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner
   */
  attributes?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributes;
}

/**
 * Check if a given object implements the EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner interface.
 */
export function instanceOfEventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSON(
  json: any
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner {
  return EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerToJSON(
  value?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInner | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesToJSON(
        value.attributes
      ),
  };
}
