/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddress } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddress";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddressFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddressFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddressToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddress";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";

/**
 *
 * @export
 * @interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
 */
export interface EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes {
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  name?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddress}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  address?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddress;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  embeddedMapUrl?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  logo?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  website?: string;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  socialNetworks?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  events?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  shortName?: string;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes interface.
 */
export function instanceOfEventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSON(
  json: any
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes {
  return EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSONTyped(
    json,
    false
  );
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    address: !exists(json, "address")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddressFromJSON(
          json["address"]
        ),
    embeddedMapUrl: !exists(json, "embeddedMapUrl")
      ? undefined
      : json["embeddedMapUrl"],
    logo: !exists(json, "logo")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON(
          json["logo"]
        ),
    website: !exists(json, "website") ? undefined : json["website"],
    socialNetworks: !exists(json, "socialNetworks")
      ? undefined
      : (json["socialNetworks"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON
        ),
    events: !exists(json, "events")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["events"]
        ),
    country: !exists(json, "country") ? undefined : json["country"],
    shortName: !exists(json, "shortName") ? undefined : json["shortName"],
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesToJSON(
  value?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    address:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesAddressToJSON(
        value.address
      ),
    embeddedMapUrl: value.embeddedMapUrl,
    logo: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON(
      value.logo
    ),
    website: value.website,
    socialNetworks:
      value.socialNetworks === undefined
        ? undefined
        : (value.socialNetworks as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON
          ),
    events: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.events
    ),
    country: value.country,
    shortName: value.shortName,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
