/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { PlayerListResponseDataItemAttributes } from "./PlayerListResponseDataItemAttributes";
import {
  PlayerListResponseDataItemAttributesFromJSON,
  PlayerListResponseDataItemAttributesFromJSONTyped,
  PlayerListResponseDataItemAttributesToJSON,
} from "./PlayerListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface PlayerListResponseDataItem
 */
export interface PlayerListResponseDataItem {
  /**
   *
   * @type {number}
   * @memberof PlayerListResponseDataItem
   */
  id?: number;
  /**
   *
   * @type {PlayerListResponseDataItemAttributes}
   * @memberof PlayerListResponseDataItem
   */
  attributes?: PlayerListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the PlayerListResponseDataItem interface.
 */
export function instanceOfPlayerListResponseDataItem(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PlayerListResponseDataItemFromJSON(
  json: any
): PlayerListResponseDataItem {
  return PlayerListResponseDataItemFromJSONTyped(json, false);
}

export function PlayerListResponseDataItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PlayerListResponseDataItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : PlayerListResponseDataItemAttributesFromJSON(json["attributes"]),
  };
}

export function PlayerListResponseDataItemToJSON(
  value?: PlayerListResponseDataItem | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: PlayerListResponseDataItemAttributesToJSON(value.attributes),
  };
}
