/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseMeta } from "./EventListResponseMeta";
import {
  EventListResponseMetaFromJSON,
  EventListResponseMetaFromJSONTyped,
  EventListResponseMetaToJSON,
} from "./EventListResponseMeta";
import type { PlayerListResponseDataItem } from "./PlayerListResponseDataItem";
import {
  PlayerListResponseDataItemFromJSON,
  PlayerListResponseDataItemFromJSONTyped,
  PlayerListResponseDataItemToJSON,
} from "./PlayerListResponseDataItem";

/**
 *
 * @export
 * @interface PlayerListResponse
 */
export interface PlayerListResponse {
  /**
   *
   * @type {Array<PlayerListResponseDataItem>}
   * @memberof PlayerListResponse
   */
  data?: Array<PlayerListResponseDataItem>;
  /**
   *
   * @type {EventListResponseMeta}
   * @memberof PlayerListResponse
   */
  meta?: EventListResponseMeta;
}

/**
 * Check if a given object implements the PlayerListResponse interface.
 */
export function instanceOfPlayerListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PlayerListResponseFromJSON(json: any): PlayerListResponse {
  return PlayerListResponseFromJSONTyped(json, false);
}

export function PlayerListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PlayerListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(PlayerListResponseDataItemFromJSON),
    meta: !exists(json, "meta")
      ? undefined
      : EventListResponseMetaFromJSON(json["meta"]),
  };
}

export function PlayerListResponseToJSON(
  value?: PlayerListResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(PlayerListResponseDataItemToJSON),
    meta: EventListResponseMetaToJSON(value.meta),
  };
}
