/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { SponsorListResponseDataItemAttributes } from "./SponsorListResponseDataItemAttributes";
import {
  SponsorListResponseDataItemAttributesFromJSON,
  SponsorListResponseDataItemAttributesFromJSONTyped,
  SponsorListResponseDataItemAttributesToJSON,
} from "./SponsorListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface SponsorListResponseDataItemLocalized
 */
export interface SponsorListResponseDataItemLocalized {
  /**
   *
   * @type {number}
   * @memberof SponsorListResponseDataItemLocalized
   */
  id?: number;
  /**
   *
   * @type {SponsorListResponseDataItemAttributes}
   * @memberof SponsorListResponseDataItemLocalized
   */
  attributes?: SponsorListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the SponsorListResponseDataItemLocalized interface.
 */
export function instanceOfSponsorListResponseDataItemLocalized(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function SponsorListResponseDataItemLocalizedFromJSON(
  json: any
): SponsorListResponseDataItemLocalized {
  return SponsorListResponseDataItemLocalizedFromJSONTyped(json, false);
}

export function SponsorListResponseDataItemLocalizedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SponsorListResponseDataItemLocalized {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : SponsorListResponseDataItemAttributesFromJSON(json["attributes"]),
  };
}

export function SponsorListResponseDataItemLocalizedToJSON(
  value?: SponsorListResponseDataItemLocalized | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: SponsorListResponseDataItemAttributesToJSON(value.attributes),
  };
}
