/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { ContactSocialNetworkComponent } from "./ContactSocialNetworkComponent";
import {
  ContactSocialNetworkComponentFromJSON,
  ContactSocialNetworkComponentFromJSONTyped,
  ContactSocialNetworkComponentToJSON,
} from "./ContactSocialNetworkComponent";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";

/**
 *
 * @export
 * @interface SponsorListResponseDataItemAttributes
 */
export interface SponsorListResponseDataItemAttributes {
  /**
   *
   * @type {string}
   * @memberof SponsorListResponseDataItemAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof SponsorListResponseDataItemAttributes
   */
  url?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo}
   * @memberof SponsorListResponseDataItemAttributes
   */
  logo?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo;
  /**
   *
   * @type {Array<ContactSocialNetworkComponent>}
   * @memberof SponsorListResponseDataItemAttributes
   */
  socialNetworks?: Array<ContactSocialNetworkComponent>;
  /**
   *
   * @type {Date}
   * @memberof SponsorListResponseDataItemAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof SponsorListResponseDataItemAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy}
   * @memberof SponsorListResponseDataItemAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedBy;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof SponsorListResponseDataItemAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the SponsorListResponseDataItemAttributes interface.
 */
export function instanceOfSponsorListResponseDataItemAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function SponsorListResponseDataItemAttributesFromJSON(
  json: any
): SponsorListResponseDataItemAttributes {
  return SponsorListResponseDataItemAttributesFromJSONTyped(json, false);
}

export function SponsorListResponseDataItemAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SponsorListResponseDataItemAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    url: !exists(json, "url") ? undefined : json["url"],
    logo: !exists(json, "logo")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON(
          json["logo"]
        ),
    socialNetworks: !exists(json, "socialNetworks")
      ? undefined
      : (json["socialNetworks"] as Array<any>).map(
          ContactSocialNetworkComponentFromJSON
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function SponsorListResponseDataItemAttributesToJSON(
  value?: SponsorListResponseDataItemAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    url: value.url,
    logo: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON(
      value.logo
    ),
    socialNetworks:
      value.socialNetworks === undefined
        ? undefined
        : (value.socialNetworks as Array<any>).map(
            ContactSocialNetworkComponentToJSON
          ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
