/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UploadFileResponseDataObject } from "./UploadFileResponseDataObject";
import {
  UploadFileResponseDataObjectFromJSON,
  UploadFileResponseDataObjectFromJSONTyped,
  UploadFileResponseDataObjectToJSON,
} from "./UploadFileResponseDataObject";

/**
 *
 * @export
 * @interface UploadFileResponse
 */
export interface UploadFileResponse {
  /**
   *
   * @type {UploadFileResponseDataObject}
   * @memberof UploadFileResponse
   */
  data?: UploadFileResponseDataObject;
  /**
   *
   * @type {object}
   * @memberof UploadFileResponse
   */
  meta?: object;
}

/**
 * Check if a given object implements the UploadFileResponse interface.
 */
export function instanceOfUploadFileResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UploadFileResponseFromJSON(json: any): UploadFileResponse {
  return UploadFileResponseFromJSONTyped(json, false);
}

export function UploadFileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFileResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : UploadFileResponseDataObjectFromJSON(json["data"]),
    meta: !exists(json, "meta") ? undefined : json["meta"],
  };
}

export function UploadFileResponseToJSON(
  value?: UploadFileResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UploadFileResponseDataObjectToJSON(value.data),
    meta: value.meta,
  };
}
