/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributes } from "./EventLocalizationResponseImagesDataInnerAttributes";
import {
  EventLocalizationResponseImagesDataInnerAttributesFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributes";

/**
 *
 * @export
 * @interface UploadFileListResponseDataItem
 */
export interface UploadFileListResponseDataItem {
  /**
   *
   * @type {number}
   * @memberof UploadFileListResponseDataItem
   */
  id?: number;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributes}
   * @memberof UploadFileListResponseDataItem
   */
  attributes?: EventLocalizationResponseImagesDataInnerAttributes;
}

/**
 * Check if a given object implements the UploadFileListResponseDataItem interface.
 */
export function instanceOfUploadFileListResponseDataItem(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UploadFileListResponseDataItemFromJSON(
  json: any
): UploadFileListResponseDataItem {
  return UploadFileListResponseDataItemFromJSONTyped(json, false);
}

export function UploadFileListResponseDataItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFileListResponseDataItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function UploadFileListResponseDataItemToJSON(
  value?: UploadFileListResponseDataItem | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: EventLocalizationResponseImagesDataInnerAttributesToJSON(
      value.attributes
    ),
  };
}
