/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UploadFileRequestData } from "./UploadFileRequestData";
import {
  UploadFileRequestDataFromJSON,
  UploadFileRequestDataFromJSONTyped,
  UploadFileRequestDataToJSON,
} from "./UploadFileRequestData";

/**
 *
 * @export
 * @interface UploadFileRequest
 */
export interface UploadFileRequest {
  /**
   *
   * @type {UploadFileRequestData}
   * @memberof UploadFileRequest
   */
  data: UploadFileRequestData;
}

/**
 * Check if a given object implements the UploadFileRequest interface.
 */
export function instanceOfUploadFileRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;

  return isInstance;
}

export function UploadFileRequestFromJSON(json: any): UploadFileRequest {
  return UploadFileRequestFromJSONTyped(json, false);
}

export function UploadFileRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFileRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: UploadFileRequestDataFromJSON(json["data"]),
  };
}

export function UploadFileRequestToJSON(value?: UploadFileRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UploadFileRequestDataToJSON(value.data),
  };
}
