/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseMeta } from "./EventListResponseMeta";
import {
  EventListResponseMetaFromJSON,
  EventListResponseMetaFromJSONTyped,
  EventListResponseMetaToJSON,
} from "./EventListResponseMeta";
import type { UploadFolderListResponseDataItem } from "./UploadFolderListResponseDataItem";
import {
  UploadFolderListResponseDataItemFromJSON,
  UploadFolderListResponseDataItemFromJSONTyped,
  UploadFolderListResponseDataItemToJSON,
} from "./UploadFolderListResponseDataItem";

/**
 *
 * @export
 * @interface UploadFolderListResponse
 */
export interface UploadFolderListResponse {
  /**
   *
   * @type {Array<UploadFolderListResponseDataItem>}
   * @memberof UploadFolderListResponse
   */
  data?: Array<UploadFolderListResponseDataItem>;
  /**
   *
   * @type {EventListResponseMeta}
   * @memberof UploadFolderListResponse
   */
  meta?: EventListResponseMeta;
}

/**
 * Check if a given object implements the UploadFolderListResponse interface.
 */
export function instanceOfUploadFolderListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UploadFolderListResponseFromJSON(
  json: any
): UploadFolderListResponse {
  return UploadFolderListResponseFromJSONTyped(json, false);
}

export function UploadFolderListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFolderListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UploadFolderListResponseDataItemFromJSON
        ),
    meta: !exists(json, "meta")
      ? undefined
      : EventListResponseMetaFromJSON(json["meta"]),
  };
}

export function UploadFolderListResponseToJSON(
  value?: UploadFolderListResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UploadFolderListResponseDataItemToJSON
          ),
    meta: EventListResponseMetaToJSON(value.meta),
  };
}
