/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolder } from "./EventLocalizationResponseImagesDataInnerAttributesFolder";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolder";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";

/**
 *
 * @export
 * @interface UploadFolderListResponseDataItemAttributes
 */
export interface UploadFolderListResponseDataItemAttributes {
  /**
   *
   * @type {string}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  pathId?: number;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolder}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  parent?: EventLocalizationResponseImagesDataInnerAttributesFolder;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  children?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  files?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {string}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  path?: string;
  /**
   *
   * @type {Date}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UploadFolderListResponseDataItemAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the UploadFolderListResponseDataItemAttributes interface.
 */
export function instanceOfUploadFolderListResponseDataItemAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UploadFolderListResponseDataItemAttributesFromJSON(
  json: any
): UploadFolderListResponseDataItemAttributes {
  return UploadFolderListResponseDataItemAttributesFromJSONTyped(json, false);
}

export function UploadFolderListResponseDataItemAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UploadFolderListResponseDataItemAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    pathId: !exists(json, "pathId") ? undefined : json["pathId"],
    parent: !exists(json, "parent")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderFromJSON(
          json["parent"]
        ),
    children: !exists(json, "children")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["children"]
        ),
    files: !exists(json, "files")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["files"]
        ),
    path: !exists(json, "path") ? undefined : json["path"],
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function UploadFolderListResponseDataItemAttributesToJSON(
  value?: UploadFolderListResponseDataItemAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    pathId: value.pathId,
    parent: EventLocalizationResponseImagesDataInnerAttributesFolderToJSON(
      value.parent
    ),
    children: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.children
    ),
    files: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.files
    ),
    path: value.path,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
