/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseMeta } from "./EventListResponseMeta";
import {
  EventListResponseMetaFromJSON,
  EventListResponseMetaFromJSONTyped,
  EventListResponseMetaToJSON,
} from "./EventListResponseMeta";
import type { UsersPermissionsPermissionListResponseDataItem } from "./UsersPermissionsPermissionListResponseDataItem";
import {
  UsersPermissionsPermissionListResponseDataItemFromJSON,
  UsersPermissionsPermissionListResponseDataItemFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemToJSON,
} from "./UsersPermissionsPermissionListResponseDataItem";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponse
 */
export interface UsersPermissionsPermissionListResponse {
  /**
   *
   * @type {Array<UsersPermissionsPermissionListResponseDataItem>}
   * @memberof UsersPermissionsPermissionListResponse
   */
  data?: Array<UsersPermissionsPermissionListResponseDataItem>;
  /**
   *
   * @type {EventListResponseMeta}
   * @memberof UsersPermissionsPermissionListResponse
   */
  meta?: EventListResponseMeta;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponse interface.
 */
export function instanceOfUsersPermissionsPermissionListResponse(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseFromJSON(
  json: any
): UsersPermissionsPermissionListResponse {
  return UsersPermissionsPermissionListResponseFromJSONTyped(json, false);
}

export function UsersPermissionsPermissionListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UsersPermissionsPermissionListResponseDataItemFromJSON
        ),
    meta: !exists(json, "meta")
      ? undefined
      : EventListResponseMetaFromJSON(json["meta"]),
  };
}

export function UsersPermissionsPermissionListResponseToJSON(
  value?: UsersPermissionsPermissionListResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UsersPermissionsPermissionListResponseDataItemToJSON
          ),
    meta: EventListResponseMetaToJSON(value.meta),
  };
}
