/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerData } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerData";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerData";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer {
  /**
   *
   * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerData}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer
   */
  data?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerData;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataFromJSON(
          json["data"]
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataToJSON(
      value.data
    ),
  };
}
