/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInner } from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInner";
import {
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerFromJSON,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerFromJSONTyped,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerToJSON,
} from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInner";

/**
 *
 * @export
 * @interface UsersPermissionsRoleListResponseDataItemAttributesPermissions
 */
export interface UsersPermissionsRoleListResponseDataItemAttributesPermissions {
  /**
   *
   * @type {Array<UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInner>}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissions
   */
  data?: Array<UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInner>;
}

/**
 * Check if a given object implements the UsersPermissionsRoleListResponseDataItemAttributesPermissions interface.
 */
export function instanceOfUsersPermissionsRoleListResponseDataItemAttributesPermissions(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsFromJSON(
  json: any
): UsersPermissionsRoleListResponseDataItemAttributesPermissions {
  return UsersPermissionsRoleListResponseDataItemAttributesPermissionsFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRoleListResponseDataItemAttributesPermissions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerFromJSON
        ),
  };
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsToJSON(
  value?: UsersPermissionsRoleListResponseDataItemAttributesPermissions | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerToJSON
          ),
  };
}
