/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInner } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInner";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInner";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers {
  /**
   *
   * @type {Array<UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInner>}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers
   */
  data?: Array<UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInner>;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerFromJSON
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsers | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerToJSON
          ),
  };
}
