/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsers } from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsers";
import {
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsersFromJSON,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsersFromJSONTyped,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsersToJSON,
} from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsers";

/**
 *
 * @export
 * @interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
 */
export interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes {
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  type?: string;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  permissions?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsers}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  users?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsers;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes interface.
 */
export function instanceOfUsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesFromJSON(
  json: any
): UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes {
  return UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    type: !exists(json, "type") ? undefined : json["type"],
    permissions: !exists(json, "permissions")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["permissions"]
        ),
    users: !exists(json, "users")
      ? undefined
      : UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsersFromJSON(
          json["users"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesToJSON(
  value?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    type: value.type,
    permissions:
      EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
        value.permissions
      ),
    users:
      UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataAttributesUsersToJSON(
        value.users
      ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
