/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Datetime } from "./Datetime";
import {
  DatetimeFromJSON,
  DatetimeFromJSONTyped,
  DatetimeToJSON,
} from "./Datetime";

/**
 *
 * @export
 * @interface UsersPermissionsRole
 */
export interface UsersPermissionsRole {
  /**
   *
   * @type {number}
   * @memberof UsersPermissionsRole
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRole
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRole
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsRole
   */
  type?: string;
  /**
   *
   * @type {Datetime}
   * @memberof UsersPermissionsRole
   */
  createdAt?: Datetime;
  /**
   *
   * @type {Datetime}
   * @memberof UsersPermissionsRole
   */
  updatedAt?: Datetime;
}

/**
 * Check if a given object implements the UsersPermissionsRole interface.
 */
export function instanceOfUsersPermissionsRole(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsRoleFromJSON(json: any): UsersPermissionsRole {
  return UsersPermissionsRoleFromJSONTyped(json, false);
}

export function UsersPermissionsRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRole {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    type: !exists(json, "type") ? undefined : json["type"],
    createdAt: !exists(json, "createdAt")
      ? undefined
      : DatetimeFromJSON(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : DatetimeFromJSON(json["updatedAt"]),
  };
}

export function UsersPermissionsRoleToJSON(
  value?: UsersPermissionsRole | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
    type: value.type,
    createdAt: DatetimeToJSON(value.createdAt),
    updatedAt: DatetimeToJSON(value.updatedAt),
  };
}
