/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionListResponseDataItemAttributes } from "./UsersPermissionsPermissionListResponseDataItemAttributes";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionResponseDataObject
 */
export interface UsersPermissionsPermissionResponseDataObject {
  /**
   *
   * @type {number}
   * @memberof UsersPermissionsPermissionResponseDataObject
   */
  id?: number;
  /**
   *
   * @type {UsersPermissionsPermissionListResponseDataItemAttributes}
   * @memberof UsersPermissionsPermissionResponseDataObject
   */
  attributes?: UsersPermissionsPermissionListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionResponseDataObject interface.
 */
export function instanceOfUsersPermissionsPermissionResponseDataObject(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionResponseDataObjectFromJSON(
  json: any
): UsersPermissionsPermissionResponseDataObject {
  return UsersPermissionsPermissionResponseDataObjectFromJSONTyped(json, false);
}

export function UsersPermissionsPermissionResponseDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionResponseDataObject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : UsersPermissionsPermissionListResponseDataItemAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function UsersPermissionsPermissionResponseDataObjectToJSON(
  value?: UsersPermissionsPermissionResponseDataObject | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: UsersPermissionsPermissionListResponseDataItemAttributesToJSON(
      value.attributes
    ),
  };
}
