/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleData } from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleData";
import {
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataFromJSON,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataFromJSONTyped,
  UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataToJSON,
} from "./UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleData";

/**
 *
 * @export
 * @interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole
 */
export interface UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole {
  /**
   *
   * @type {UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleData}
   * @memberof UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole
   */
  data?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleData;
}

/**
 * Check if a given object implements the UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole interface.
 */
export function instanceOfUsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleFromJSON(
  json: any
): UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole {
  return UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataFromJSON(
          json["data"]
        ),
  };
}

export function UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleToJSON(
  value?: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRole | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UsersPermissionsRoleListResponseDataItemAttributesPermissionsDataInnerAttributesRoleDataToJSON(
      value.data
    ),
  };
}
