/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { EventLocalizationResponseImagesDataInnerAttributesRelated } from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import {
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesRelated";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo";
import type { EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner } from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";
import {
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSONTyped,
  EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON,
} from "./EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEvents } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEvents";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEventsFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEventsFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEventsToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEvents";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes {
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  slug?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  position?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesPositionEnum;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  company?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  tagline?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  bio?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  country?: string;
  /**
   *
   * @type {EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  avatar?: EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogo;
  /**
   *
   * @type {Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  socialNetworks?: Array<EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInner>;
  /**
   *
   * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEvents}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  events?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEvents;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  hosted?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesRelated}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  mentored?: EventLocalizationResponseImagesDataInnerAttributesRelated;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  user?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * @export
 */
export const UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesPositionEnum =
  {
    Player: "Player",
    Host: "Host",
    Mentor: "Mentor",
    Founder: "Founder",
  } as const;
export type UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesPositionEnum =
  typeof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesPositionEnum[keyof typeof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesPositionEnum];

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    slug: !exists(json, "slug") ? undefined : json["slug"],
    position: !exists(json, "position") ? undefined : json["position"],
    company: !exists(json, "company") ? undefined : json["company"],
    tagline: !exists(json, "tagline") ? undefined : json["tagline"],
    bio: !exists(json, "bio") ? undefined : json["bio"],
    country: !exists(json, "country") ? undefined : json["country"],
    avatar: !exists(json, "avatar")
      ? undefined
      : EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoFromJSON(
          json["avatar"]
        ),
    socialNetworks: !exists(json, "socialNetworks")
      ? undefined
      : (json["socialNetworks"] as Array<any>).map(
          EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerFromJSON
        ),
    events: !exists(json, "events")
      ? undefined
      : UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEventsFromJSON(
          json["events"]
        ),
    hosted: !exists(json, "hosted")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["hosted"]
        ),
    mentored: !exists(json, "mentored")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesRelatedFromJSON(
          json["mentored"]
        ),
    user: !exists(json, "user")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["user"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    slug: value.slug,
    position: value.position,
    company: value.company,
    tagline: value.tagline,
    bio: value.bio,
    country: value.country,
    avatar:
      EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesLogoToJSON(
        value.avatar
      ),
    socialNetworks:
      value.socialNetworks === undefined
        ? undefined
        : (value.socialNetworks as Array<any>).map(
            EventLocalizationResponseLocationDataAttributesEventsDataInnerAttributesVenueDataAttributesSocialNetworksInnerToJSON
          ),
    events:
      UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerDataAttributesEventsToJSON(
        value.events
      ),
    hosted: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.hosted
    ),
    mentored: EventLocalizationResponseImagesDataInnerAttributesRelatedToJSON(
      value.mentored
    ),
    user: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
      value.user
    ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
