/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInner } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInner";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInnerFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInnerFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInnerToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInner";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions {
  /**
   *
   * @type {Array<UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInner>}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions
   */
  data?: Array<UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInner>;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInnerFromJSON
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissions | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesPermissionsDataInnerToJSON
          ),
  };
}
