/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseMeta } from "./EventListResponseMeta";
import {
  EventListResponseMetaFromJSON,
  EventListResponseMetaFromJSONTyped,
  EventListResponseMetaToJSON,
} from "./EventListResponseMeta";
import type { UsersPermissionsRoleListResponseDataItem } from "./UsersPermissionsRoleListResponseDataItem";
import {
  UsersPermissionsRoleListResponseDataItemFromJSON,
  UsersPermissionsRoleListResponseDataItemFromJSONTyped,
  UsersPermissionsRoleListResponseDataItemToJSON,
} from "./UsersPermissionsRoleListResponseDataItem";

/**
 *
 * @export
 * @interface UsersPermissionsRoleListResponse
 */
export interface UsersPermissionsRoleListResponse {
  /**
   *
   * @type {Array<UsersPermissionsRoleListResponseDataItem>}
   * @memberof UsersPermissionsRoleListResponse
   */
  data?: Array<UsersPermissionsRoleListResponseDataItem>;
  /**
   *
   * @type {EventListResponseMeta}
   * @memberof UsersPermissionsRoleListResponse
   */
  meta?: EventListResponseMeta;
}

/**
 * Check if a given object implements the UsersPermissionsRoleListResponse interface.
 */
export function instanceOfUsersPermissionsRoleListResponse(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsRoleListResponseFromJSON(
  json: any
): UsersPermissionsRoleListResponse {
  return UsersPermissionsRoleListResponseFromJSONTyped(json, false);
}

export function UsersPermissionsRoleListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRoleListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          UsersPermissionsRoleListResponseDataItemFromJSON
        ),
    meta: !exists(json, "meta")
      ? undefined
      : EventListResponseMetaFromJSON(json["meta"]),
  };
}

export function UsersPermissionsRoleListResponseToJSON(
  value?: UsersPermissionsRoleListResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(
            UsersPermissionsRoleListResponseDataItemToJSON
          ),
    meta: EventListResponseMetaToJSON(value.meta),
  };
}
