/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsRoleRequestData } from "./UsersPermissionsRoleRequestData";
import {
  UsersPermissionsRoleRequestDataFromJSON,
  UsersPermissionsRoleRequestDataFromJSONTyped,
  UsersPermissionsRoleRequestDataToJSON,
} from "./UsersPermissionsRoleRequestData";

/**
 *
 * @export
 * @interface UsersPermissionsRoleRequest
 */
export interface UsersPermissionsRoleRequest {
  /**
   *
   * @type {UsersPermissionsRoleRequestData}
   * @memberof UsersPermissionsRoleRequest
   */
  data: UsersPermissionsRoleRequestData;
}

/**
 * Check if a given object implements the UsersPermissionsRoleRequest interface.
 */
export function instanceOfUsersPermissionsRoleRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "data" in value;

  return isInstance;
}

export function UsersPermissionsRoleRequestFromJSON(
  json: any
): UsersPermissionsRoleRequest {
  return UsersPermissionsRoleRequestFromJSONTyped(json, false);
}

export function UsersPermissionsRoleRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsRoleRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: UsersPermissionsRoleRequestDataFromJSON(json["data"]),
  };
}

export function UsersPermissionsRoleRequestToJSON(
  value?: UsersPermissionsRoleRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UsersPermissionsRoleRequestDataToJSON(value.data),
  };
}
