/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsUserListResponseDataItemAttributes } from "./UsersPermissionsUserListResponseDataItemAttributes";
import {
  UsersPermissionsUserListResponseDataItemAttributesFromJSON,
  UsersPermissionsUserListResponseDataItemAttributesFromJSONTyped,
  UsersPermissionsUserListResponseDataItemAttributesToJSON,
} from "./UsersPermissionsUserListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface UsersPermissionsUserResponseDataObject
 */
export interface UsersPermissionsUserResponseDataObject {
  /**
   *
   * @type {number}
   * @memberof UsersPermissionsUserResponseDataObject
   */
  id?: number;
  /**
   *
   * @type {UsersPermissionsUserListResponseDataItemAttributes}
   * @memberof UsersPermissionsUserResponseDataObject
   */
  attributes?: UsersPermissionsUserListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the UsersPermissionsUserResponseDataObject interface.
 */
export function instanceOfUsersPermissionsUserResponseDataObject(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsUserResponseDataObjectFromJSON(
  json: any
): UsersPermissionsUserResponseDataObject {
  return UsersPermissionsUserResponseDataObjectFromJSONTyped(json, false);
}

export function UsersPermissionsUserResponseDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsUserResponseDataObject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : UsersPermissionsUserListResponseDataItemAttributesFromJSON(
          json["attributes"]
        ),
  };
}

export function UsersPermissionsUserResponseDataObjectToJSON(
  value?: UsersPermissionsUserResponseDataObject | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: UsersPermissionsUserListResponseDataItemAttributesToJSON(
      value.attributes
    ),
  };
}
