/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleData } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleData";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleData";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRole
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRole {
  /**
   *
   * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleData}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRole
   */
  data?: UsersPermissionsPermissionListResponseDataItemAttributesRoleData;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRole interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRole(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRole {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRole {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : UsersPermissionsPermissionListResponseDataItemAttributesRoleDataFromJSON(
          json["data"]
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRole | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataToJSON(
      value.data
    ),
  };
}
