/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent } from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import {
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
  EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON,
} from "./EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent";
import type { UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer } from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer";
import {
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSON,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSONTyped,
  UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerToJSON,
} from "./UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
 */
export interface UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes {
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  provider?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  resetPasswordToken?: string;
  /**
   *
   * @type {string}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  confirmationToken?: string;
  /**
   *
   * @type {boolean}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  confirmed?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  blocked?: boolean;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  role?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  player?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayer;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  updatedAt?: Date;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  createdBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
  /**
   *
   * @type {EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent}
   * @memberof UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes
   */
  updatedBy?: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes interface.
 */
export function instanceOfUsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesFromJSON(
  json: any
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes {
  return UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesFromJSONTyped(
    json,
    false
  );
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: !exists(json, "username") ? undefined : json["username"],
    email: !exists(json, "email") ? undefined : json["email"],
    provider: !exists(json, "provider") ? undefined : json["provider"],
    resetPasswordToken: !exists(json, "resetPasswordToken")
      ? undefined
      : json["resetPasswordToken"],
    confirmationToken: !exists(json, "confirmationToken")
      ? undefined
      : json["confirmationToken"],
    confirmed: !exists(json, "confirmed") ? undefined : json["confirmed"],
    blocked: !exists(json, "blocked") ? undefined : json["blocked"],
    role: !exists(json, "role")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["role"]
        ),
    player: !exists(json, "player")
      ? undefined
      : UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerFromJSON(
          json["player"]
        ),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
    createdBy: !exists(json, "createdBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["createdBy"]
        ),
    updatedBy: !exists(json, "updatedBy")
      ? undefined
      : EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentFromJSON(
          json["updatedBy"]
        ),
  };
}

export function UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesToJSON(
  value?: UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributes | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    email: value.email,
    provider: value.provider,
    resetPasswordToken: value.resetPasswordToken,
    confirmationToken: value.confirmationToken,
    confirmed: value.confirmed,
    blocked: value.blocked,
    role: EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
      value.role
    ),
    player:
      UsersPermissionsPermissionListResponseDataItemAttributesRoleDataAttributesUsersDataInnerAttributesPlayerToJSON(
        value.player
      ),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
    createdBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.createdBy
      ),
    updatedBy:
      EventLocalizationResponseImagesDataInnerAttributesFolderDataAttributesParentToJSON(
        value.updatedBy
      ),
  };
}
