/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UsersPermissionsPermissionResponseDataObject } from "./UsersPermissionsPermissionResponseDataObject";
import {
  UsersPermissionsPermissionResponseDataObjectFromJSON,
  UsersPermissionsPermissionResponseDataObjectFromJSONTyped,
  UsersPermissionsPermissionResponseDataObjectToJSON,
} from "./UsersPermissionsPermissionResponseDataObject";

/**
 *
 * @export
 * @interface UsersPermissionsPermissionResponse
 */
export interface UsersPermissionsPermissionResponse {
  /**
   *
   * @type {UsersPermissionsPermissionResponseDataObject}
   * @memberof UsersPermissionsPermissionResponse
   */
  data?: UsersPermissionsPermissionResponseDataObject;
  /**
   *
   * @type {object}
   * @memberof UsersPermissionsPermissionResponse
   */
  meta?: object;
}

/**
 * Check if a given object implements the UsersPermissionsPermissionResponse interface.
 */
export function instanceOfUsersPermissionsPermissionResponse(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function UsersPermissionsPermissionResponseFromJSON(
  json: any
): UsersPermissionsPermissionResponse {
  return UsersPermissionsPermissionResponseFromJSONTyped(json, false);
}

export function UsersPermissionsPermissionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsersPermissionsPermissionResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : UsersPermissionsPermissionResponseDataObjectFromJSON(json["data"]),
    meta: !exists(json, "meta") ? undefined : json["meta"],
  };
}

export function UsersPermissionsPermissionResponseToJSON(
  value?: UsersPermissionsPermissionResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: UsersPermissionsPermissionResponseDataObjectToJSON(value.data),
    meta: value.meta,
  };
}
