/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EventListResponseMeta } from "./EventListResponseMeta";
import {
  EventListResponseMetaFromJSON,
  EventListResponseMetaFromJSONTyped,
  EventListResponseMetaToJSON,
} from "./EventListResponseMeta";
import type { VenueListResponseDataItem } from "./VenueListResponseDataItem";
import {
  VenueListResponseDataItemFromJSON,
  VenueListResponseDataItemFromJSONTyped,
  VenueListResponseDataItemToJSON,
} from "./VenueListResponseDataItem";

/**
 *
 * @export
 * @interface VenueListResponse
 */
export interface VenueListResponse {
  /**
   *
   * @type {Array<VenueListResponseDataItem>}
   * @memberof VenueListResponse
   */
  data?: Array<VenueListResponseDataItem>;
  /**
   *
   * @type {EventListResponseMeta}
   * @memberof VenueListResponse
   */
  meta?: EventListResponseMeta;
}

/**
 * Check if a given object implements the VenueListResponse interface.
 */
export function instanceOfVenueListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VenueListResponseFromJSON(json: any): VenueListResponse {
  return VenueListResponseFromJSONTyped(json, false);
}

export function VenueListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VenueListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(VenueListResponseDataItemFromJSON),
    meta: !exists(json, "meta")
      ? undefined
      : EventListResponseMetaFromJSON(json["meta"]),
  };
}

export function VenueListResponseToJSON(value?: VenueListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(VenueListResponseDataItemToJSON),
    meta: EventListResponseMetaToJSON(value.meta),
  };
}
