/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { VenueListResponseDataItemAttributes } from "./VenueListResponseDataItemAttributes";
import {
  VenueListResponseDataItemAttributesFromJSON,
  VenueListResponseDataItemAttributesFromJSONTyped,
  VenueListResponseDataItemAttributesToJSON,
} from "./VenueListResponseDataItemAttributes";

/**
 *
 * @export
 * @interface VenueResponseDataObject
 */
export interface VenueResponseDataObject {
  /**
   *
   * @type {number}
   * @memberof VenueResponseDataObject
   */
  id?: number;
  /**
   *
   * @type {VenueListResponseDataItemAttributes}
   * @memberof VenueResponseDataObject
   */
  attributes?: VenueListResponseDataItemAttributes;
}

/**
 * Check if a given object implements the VenueResponseDataObject interface.
 */
export function instanceOfVenueResponseDataObject(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VenueResponseDataObjectFromJSON(
  json: any
): VenueResponseDataObject {
  return VenueResponseDataObjectFromJSONTyped(json, false);
}

export function VenueResponseDataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VenueResponseDataObject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    attributes: !exists(json, "attributes")
      ? undefined
      : VenueListResponseDataItemAttributesFromJSON(json["attributes"]),
  };
}

export function VenueResponseDataObjectToJSON(
  value?: VenueResponseDataObject | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    attributes: VenueListResponseDataItemAttributesToJSON(value.attributes),
  };
}
