/* tslint:disable */
/* eslint-disable */
/**
 * #play14 api documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: team@play14.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  EventLocationListResponse,
  EventLocationRequest,
  EventLocationResponse,
} from "../models";
import {
  EventLocationListResponseFromJSON,
  EventLocationListResponseToJSON,
  EventLocationRequestFromJSON,
  EventLocationRequestToJSON,
  EventLocationResponseFromJSON,
  EventLocationResponseToJSON,
} from "../models";

export interface DeleteEventLocationsIdRequest {
  id: number;
}

export interface GetEventLocationsRequest {
  sort?: string;
  paginationWithCount?: boolean;
  paginationPage?: number;
  paginationPageSize?: number;
  paginationStart?: number;
  paginationLimit?: number;
  fields?: string;
  populate?: string;
  filters?: object;
  locale?: string;
}

export interface GetEventLocationsIdRequest {
  id: number;
}

export interface PostEventLocationsRequest {
  eventLocationRequest: EventLocationRequest;
}

export interface PutEventLocationsIdRequest {
  id: number;
  eventLocationRequest: EventLocationRequest;
}

/**
 *
 */
export class EventLocationApi extends runtime.BaseAPI {
  /**
   */
  async deleteEventLocationsIdRaw(
    requestParameters: DeleteEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<number>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling deleteEventLocationsId."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/event-locations/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.TextApiResponse(response) as any;
  }

  /**
   */
  async deleteEventLocationsId(
    requestParameters: DeleteEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<number> {
    const response = await this.deleteEventLocationsIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async getEventLocationsRaw(
    requestParameters: GetEventLocationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EventLocationListResponse>> {
    const queryParameters: any = {};

    if (requestParameters.sort !== undefined) {
      queryParameters["sort"] = requestParameters.sort;
    }

    if (requestParameters.paginationWithCount !== undefined) {
      queryParameters["pagination[withCount]"] =
        requestParameters.paginationWithCount;
    }

    if (requestParameters.paginationPage !== undefined) {
      queryParameters["pagination[page]"] = requestParameters.paginationPage;
    }

    if (requestParameters.paginationPageSize !== undefined) {
      queryParameters["pagination[pageSize]"] =
        requestParameters.paginationPageSize;
    }

    if (requestParameters.paginationStart !== undefined) {
      queryParameters["pagination[start]"] = requestParameters.paginationStart;
    }

    if (requestParameters.paginationLimit !== undefined) {
      queryParameters["pagination[limit]"] = requestParameters.paginationLimit;
    }

    if (requestParameters.fields !== undefined) {
      queryParameters["fields"] = requestParameters.fields;
    }

    if (requestParameters.populate !== undefined) {
      queryParameters["populate"] = requestParameters.populate;
    }

    if (requestParameters.filters !== undefined) {
      queryParameters["filters"] = requestParameters.filters;
    }

    if (requestParameters.locale !== undefined) {
      queryParameters["locale"] = requestParameters.locale;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/event-locations`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EventLocationListResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async getEventLocations(
    requestParameters: GetEventLocationsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EventLocationListResponse> {
    const response = await this.getEventLocationsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async getEventLocationsIdRaw(
    requestParameters: GetEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EventLocationResponse>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling getEventLocationsId."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/event-locations/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EventLocationResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async getEventLocationsId(
    requestParameters: GetEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EventLocationResponse> {
    const response = await this.getEventLocationsIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async postEventLocationsRaw(
    requestParameters: PostEventLocationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EventLocationResponse>> {
    if (
      requestParameters.eventLocationRequest === null ||
      requestParameters.eventLocationRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "eventLocationRequest",
        "Required parameter requestParameters.eventLocationRequest was null or undefined when calling postEventLocations."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/event-locations`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: EventLocationRequestToJSON(
          requestParameters.eventLocationRequest
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EventLocationResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async postEventLocations(
    requestParameters: PostEventLocationsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EventLocationResponse> {
    const response = await this.postEventLocationsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async putEventLocationsIdRaw(
    requestParameters: PutEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EventLocationResponse>> {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling putEventLocationsId."
      );
    }

    if (
      requestParameters.eventLocationRequest === null ||
      requestParameters.eventLocationRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "eventLocationRequest",
        "Required parameter requestParameters.eventLocationRequest was null or undefined when calling putEventLocationsId."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/event-locations/{id}`.replace(
          `{${"id"}}`,
          encodeURIComponent(String(requestParameters.id))
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: EventLocationRequestToJSON(
          requestParameters.eventLocationRequest
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EventLocationResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async putEventLocationsId(
    requestParameters: PutEventLocationsIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EventLocationResponse> {
    const response = await this.putEventLocationsIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
